version: '3.8'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    networks:
      - monitoring
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my_org
      - DOCKER_INFLUXDB_INIT_BUCKET=bitcoin
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=WOoQ8mHxpRCZ7ZybALnoFRzt4816N3JWKFx-5I02bXEXcDozy2BzlAUuH-L3ptKLYFDG4dJErZQ==
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "8186:8186"
    depends_on:
      influxdb:
        condition: service_healthy
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./dataset:/dataset:ro
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - influxdb
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  influxdb-storage:  # Define named volume for InfluxDB
  grafana-storage:   # Define named volume for Grafana