FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scripts/ ./scripts/
COPY dataset/ ./dataset/

CMD ["python", "scripts/simulate_realtime.py"]